server:
  port: 8088
  
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: product-category
          uri: lb://PRODUCT-CATEGORY
          predicates:
            - Path=/v1/product/**,/v1/category/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: product-category
                fallbackUri: forward:/fb/product-category

        - id: basket
          uri: lb://BASKET
          predicates:
            - Path=/v1/basket/**,/v1/basketProduct/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: basket
                fallbackUri: forward:/fb/basket
                
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/v1/order/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: order
                fallbackUri: forward:/fb/order
                
        - id: images
          uri: lb://IMAGES
          predicates:
            - Path=/v1/images/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: images
                fallbackUri: forward:/fb/images
                
        - id: user
          uri: lb://USER
          predicates:
            - Path=/v1/user/**,/v1/cart/**,/v1/address/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fb/user           

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
