spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/images
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
bucket.path.product: ebuozturk-ecommerce/product
image.url.product: /v1/images/product
